# Path to a directory containing the json files to be processed.
in_dir: ./path/to/jsons
# Path to the output json file.
out_file: ./path/to/output.json
# Maximum number of characters (not tokens!) in a single training prompt, before it is split into 2.
max_prompt_length: 1000
# Fraction of the data to be used for evaluation.
eval_split: 0.1
# Path to the output json file for evaluation data.
eval_out_file: ./path/to/eval_output.json
prompt: |
  <|begin_of_text|><|start_header_id|>system<|end_header_id|>

  You are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>

  I have an input JSON file I need to process. It contains an array, where each element is a snippet of a lecture video. Each element contains the keys "start_time", which denotes the start time of the snippet in seconds after video start, a "transcript" of the spoken text, and "screen_text", the text on screen as detected by OCR. The transcript and screen_text might contain inaccuracies due to the nature of STT and OCR. The video was split into snippets by detecting when the screen changes by a significant amount. Please create a JSON file containing an array of elements, where each element represents the respective snippet from the input JSON. Each element should contain a title you'd give this snippet. Choose high-quality and concise titles. If you want two back-to-back snippet to be considered as the same chapter, give them the same title in your JSON array. Remember to answer only with a JSON file. This is the input JSON:

  ```
  {json_input}
  ```<|eot_id|><|start_header_id|>assistant<|end_header_id|>

  {json_output}<|eot_id|>